name: ChangeLumberjack
version: 0.1.0
author: Adam Grieger
main: com.adamgrieger.changelumberjack.ChangeLumberjack
description: A plugin that notifies players once of each new server changelog

commands:
  cl:
    description: Main command for this plugin
    aliases: [changelumberjack, changelog]
    usage: /<command> help

permissions:
  cl.*:
    description: Gives access to all ChangeLumberjack features
    default: false